# Generated by Django 5.2.6 on 2026-08-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='local_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
