# Generated by Django 5.2.6 on 2026-08-06 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_repository_local_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=255)),
                ('extension', models.CharField(blank=True, max_length=30)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('size', models.BigIntegerField(default=0)),
                ('last_modified', models.DateTimeField()),
                ('indexed_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='repositories.repository')),
            ],
        ),
    ]
