# Generated by Django 5.2.6 on 2026-08-06 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0003_repositoryfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('start_line', models.IntegerField()),
                ('end_line', models.IntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='repositories.repositoryfile')),
            ],
        ),
    ]
