# Generated by Django 5.2.6 on 2026-08-07 18:03

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0004_codechunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('model_name', models.CharField(default='text-embedding-3-small', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='repositories.codechunk')),
            ],
        ),
    ]
