# Generated by Django 5.2.6 on 2026-08-07 20:09

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0005_codeembedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768),
        ),
    ]
